// Code generated by goctl. DO NOT EDIT.
package types

type Author struct {
	Name   string `json:"name"`
	Age    int    `json:"age"`
	Gender string `json:"gender"`
}

type AuthorRes struct {
	Author
	Id       int    `json:"id"`
	CreateAt string `json:"createAt"`
	UpdateAt string `json:"updateAt"`
}

type AuthListReq struct {
	Name     string `form:"name,optional"`
	Age      int    `form:"age,optional"`
	Gender   string `form:"gender,optional"`
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
}

type ListPaging struct {
	List     []AuthorRes `json:"list"`
	Page     int         `json:"page"`
	PageSize int         `json:"pageSize"`
	Total    int         `json:"total"`
}

type AuthListRes struct {
	Code int        `json:"code"`
	Msg  string     `json:"msg"`
	Data ListPaging `json:"data"`
}

type AuthDetailReq struct {
	Id int `path:"id"`
}

type AuthDetailRes struct {
	Code int       `json:"code"`
	Msg  string    `json:"msg"`
	Data AuthorRes `json:"data"`
}

type AuthAddReq struct {
	Author
}

type AuthAddRes struct {
	Code int       `json:"code"`
	Msg  string    `json:"msg"`
	Data AuthorRes `json:"data"`
}

type AuthUpdateReq struct {
	Id int `path:"id"`
	Author
}

type AuthUpdateRes struct {
	Code int       `json:"code"`
	Msg  string    `json:"msg"`
	Data AuthorRes `json:"data"`
}

type AuthDelReq struct {
	Id int `path:"id"`
}

type AuthDelRes struct {
	Code int       `json:"code"`
	Msg  string    `json:"msg"`
	Data AuthorRes `json:"data"`
}

type AsynqDeferTask1Req struct {
	Payload string `json:"payload"`
}

type AsynqDeferTask1Res struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
