// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go_zero_t2/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/author/list",
				Handler: AuthorListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/author/:id",
				Handler: AuthorDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/author",
				Handler: AuthorAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/author/:id",
				Handler: AuthorUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/author/:id",
				Handler: AuthorDelHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/asynq/defer/task1",
				Handler: AsynqDeferHandler(serverCtx),
			},
		},
	)
}
