// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authorBookFieldNames          = builder.RawFieldNames(&AuthorBook{})
	authorBookRows                = strings.Join(authorBookFieldNames, ",")
	authorBookRowsExpectAutoSet   = strings.Join(stringx.Remove(authorBookFieldNames, "`create_time`", "`update_time`"), ",")
	authorBookRowsWithPlaceHolder = strings.Join(stringx.Remove(authorBookFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	authorBookModel interface {
		Insert(ctx context.Context, data *AuthorBook) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AuthorBook, error)
		Update(ctx context.Context, data *AuthorBook) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAuthorBookModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AuthorBook struct {
		AuthorId sql.NullInt64 `db:"author_id"` // 作者id
		BookId   sql.NullInt64 `db:"book_id"`   // 书id
		Id       int64         `db:"id"`
	}
)

func newAuthorBookModel(conn sqlx.SqlConn) *defaultAuthorBookModel {
	return &defaultAuthorBookModel{
		conn:  conn,
		table: "`author_book`",
	}
}

func (m *defaultAuthorBookModel) Insert(ctx context.Context, data *AuthorBook) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, authorBookRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.AuthorId, data.BookId, data.Id)
	return ret, err
}

func (m *defaultAuthorBookModel) FindOne(ctx context.Context, id int64) (*AuthorBook, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authorBookRows, m.table)
	var resp AuthorBook
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthorBookModel) Update(ctx context.Context, data *AuthorBook) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, authorBookRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.AuthorId, data.BookId, data.Id)
	return err
}

func (m *defaultAuthorBookModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAuthorBookModel) tableName() string {
	return m.table
}
