// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authorFieldNames          = builder.RawFieldNames(&Author{})
	authorRows                = strings.Join(authorFieldNames, ",")
	authorRowsExpectAutoSet   = strings.Join(stringx.Remove(authorFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	authorRowsWithPlaceHolder = strings.Join(stringx.Remove(authorFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	authorModel interface {
		Insert(ctx context.Context, data *Author) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Author, error)
		FindListByCondition(ctx context.Context, condition map[string]interface{}) ([]*Author, error)
		FindListByConditionCount(ctx context.Context, condition map[string]interface{}) (int, error)
		Update(ctx context.Context, data *Author) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAuthorModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Author struct {
		Id       int64          `db:"id"`
		Name     sql.NullString `db:"name"`      // 姓名
		Age      sql.NullInt64  `db:"age"`       // 年龄
		Gender   sql.NullString `db:"gender"`    // 性别
		CreateAt sql.NullTime   `db:"create_at"` // 创建时间
		UpdateAt sql.NullTime   `db:"update_at"` // 更新时间
		DeleteAt sql.NullTime   `db:"delete_at"` // 删除时间
	}
)

func newAuthorModel(conn sqlx.SqlConn) *defaultAuthorModel {
	return &defaultAuthorModel{
		conn:  conn,
		table: "`author`",
	}
}

func (m *defaultAuthorModel) Insert(ctx context.Context, data *Author) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, authorRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Age, data.Gender, data.CreateAt, data.UpdateAt, data.DeleteAt)
	return ret, err
}

func (m *defaultAuthorModel) FindOne(ctx context.Context, id int64) (*Author, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authorRows, m.table)
	var resp Author
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthorModel) FindListByCondition(ctx context.Context, condition map[string]interface{}) ([]*Author, error) {
	query := fmt.Sprintf("select %s from %s ", authorRows, m.table)

	var subStr = ""
	// name模糊查询, age等于，gender等于
	if v, ok := condition["name"]; ok {
		subStr += fmt.Sprintf("where name like '%s'", "%"+v.(string)+"%")
	}
	if v, ok := condition["age"]; ok {
		if strings.Index(query, "where") != -1 {
			subStr += fmt.Sprintf("where age=%d", v.(int))
		} else {
			subStr += fmt.Sprintf(" and age=%d", v.(int))
		}

	}
	if v, ok := condition["gender"]; ok {
		if strings.Index(query, "where") != -1 {
			subStr += fmt.Sprintf("where gender=%s", v.(string))
		} else {
			subStr += fmt.Sprintf(" and gender=%s", v.(string))
		}
	}
	page := condition["page"].(int)
	pageSize := condition["page_size"].(int)
	subStr += fmt.Sprintf(" limit %d, %d", (page-1)*pageSize, pageSize)

	var resp []*Author
	err := m.conn.QueryRowsCtx(ctx, &resp, query+subStr)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthorModel)FindListByConditionCount(ctx context.Context, condition map[string]interface{}) (int, error){
	query := fmt.Sprintf("select count(*) from %s ", m.table)

	var subStr = ""
	// name模糊查询, age等于，gender等于
	if v, ok := condition["name"]; ok {
		subStr += fmt.Sprintf("where name like '%s'", "%"+v.(string)+"%")
	}
	if v, ok := condition["age"]; ok {
		if strings.Index(query, "where") != -1 {
			subStr += fmt.Sprintf("where age=%d", v.(int))
		} else {
			subStr += fmt.Sprintf(" and age=%d", v.(int))
		}

	}
	if v, ok := condition["gender"]; ok {
		if strings.Index(query, "where") != -1 {
			subStr += fmt.Sprintf("where gender=%s", v.(string))
		} else {
			subStr += fmt.Sprintf(" and gender=%s", v.(string))
		}
	}

	var total int
	err := m.conn.QueryRowCtx(ctx, &total, query+subStr)
	if err != nil {
		return 0, err
	}
	return total, nil
}

func (m *defaultAuthorModel) Update(ctx context.Context, data *Author) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, authorRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Age, data.Gender, data.CreateAt, data.UpdateAt, data.DeleteAt, data.Id)
	return err
}

func (m *defaultAuthorModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAuthorModel) tableName() string {
	return m.table
}
