// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bookFieldNames          = builder.RawFieldNames(&Book{})
	bookRows                = strings.Join(bookFieldNames, ",")
	bookRowsExpectAutoSet   = strings.Join(stringx.Remove(bookFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	bookRowsWithPlaceHolder = strings.Join(stringx.Remove(bookFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	bookModel interface {
		Insert(ctx context.Context, data *Book) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Book, error)
		Update(ctx context.Context, data *Book) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBookModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Book struct {
		Id       int64           `db:"id"`
		Name     sql.NullString  `db:"name"`      // 书名
		Publish  sql.NullString  `db:"publish"`   // 发布时间
		Price    sql.NullFloat64 `db:"price"`     // 价格
		CreateAt sql.NullTime    `db:"create_at"` // 创建时间
		UpdateAt sql.NullTime    `db:"update_at"` // 更新时间
		DeleteAt sql.NullTime    `db:"delete_at"` // 删除时间
	}
)

func newBookModel(conn sqlx.SqlConn) *defaultBookModel {
	return &defaultBookModel{
		conn:  conn,
		table: "`book`",
	}
}

func (m *defaultBookModel) Insert(ctx context.Context, data *Book) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, bookRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Publish, data.Price, data.CreateAt, data.UpdateAt, data.DeleteAt)
	return ret, err
}

func (m *defaultBookModel) FindOne(ctx context.Context, id int64) (*Book, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bookRows, m.table)
	var resp Book
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBookModel) Update(ctx context.Context, data *Book) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, bookRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Publish, data.Price, data.CreateAt, data.UpdateAt, data.DeleteAt, data.Id)
	return err
}

func (m *defaultBookModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBookModel) tableName() string {
	return m.table
}
